name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: ./gradlew build

      - name: Build Service A
        working-directory: ./order-service
        run: ./gradlew build

      - name: Build Service B
        working-directory: ./user-service
        run: ./gradlew build
